name: Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  push_to_registry:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build and publish to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          docker build . -t helloworld
          docker tag helloworld:latest 244530008913.dkr.ecr.eu-west-1.amazonaws.com/haha029:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/haha029:latest